version: 2

sources:
  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: account_manager_region_mapping

  - name: google_analytics
    schema: google_analytics_4
    tables:
        - name: events_2021_01_01_05
  
  - name: airbnb
    schema: airbnb
    tables:
      - name: listings

  - name: spotify
    schema: spotify
    tables:
      - name: songs
      - name: listening_data

  - name: airbnb_test
    schema: airbnb_test
    tables:
      - name: airbnb_test